
server:
  servlet:
    context-path: /mimanitas

spring:
  datasource:
    url: jdbc:h2:./mimanitas
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
  main:
    allow-circular-references: true

  sql:
    init:
      mode: never